services:
  test-runner:
    image: node:18-alpine
    working_dir: /app
    env_file: .env
    command: sh -c "npm install && npm run test:e2e"
    environment:
      GATEWAY_URL: http://gateway-service:${GATEWAY_PORT:-3003}
      REDIS_URL: redis://redis:6379
    depends_on:
      gateway-service:
        condition: service_healthy
    volumes:
      - .:/app